<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="A25" Id="{3b04d2e6-0b6c-4c36-b7dd-d9e45e2be25d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK A25 EXTENDS GenericSubarea]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^();]]></ST>
    </Implementation>
    <Method Name="callHardware" Id="{3515a28f-6599-4aad-963a-ab704995425b}">
      <Declaration><![CDATA[METHOD PROTECTED callHardware : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="runModules" Id="{13276b52-bf27-4a0b-a031-31e2c6120e0c}">
      <Declaration><![CDATA[METHOD PROTECTED runModules : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Ld"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" />
                    <l2 n="Connectors" />
                    <v n="Id">5L</v>
                  </o>
                </l2>
                <v n="BranchCounter">1</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Method>
    <Method Name="setupHardware" Id="{c528889d-6dba-45a0-ba04-14129789a879}">
      <Declaration><![CDATA[METHOD PROTECTED setupHardware : BOOL
VAR
	i : INT;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="A25">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="A25.callHardware">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="A25.setupHardware">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>