<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MatchesMaterialType" Id="{f5e34751-cdf7-4c56-b6e9-cf2209b10594}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION MatchesMaterialType : BOOL
VAR_INPUT
	pair : REFERENCE TO PositionMaterials;
	materialType : STRING;
END_VAR
VAR
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[MatchesMaterialType :=
	FIND(pair.top, materialType) > 0 AND
	FIND(pair.left, materialType) > 0 AND
	FIND(pair.right, materialType) > 0 AND
	FIND(pair.bottom, materialType) > 0 AND
	
	FIND(pair.topLeft, materialType) > 0 AND
	FIND(pair.topRight, materialType) > 0 AND
	FIND(pair.bottomLeft, materialType) > 0 AND
	FIND(pair.bottomRight, materialType) > 0 ;]]></ST>
    </Implementation>
    <LineIds Name="MatchesMaterialType">
      <LineId Id="7" Count="0" />
      <LineId Id="10" Count="3" />
      <LineId Id="18" Count="0" />
      <LineId Id="14" Count="3" />
    </LineIds>
  </POU>
</TcPlcObject>