<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="A23" Id="{1398fc59-7eb8-4b8a-923a-7c8bc34caf55}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM A23
VAR_OUTPUT //conveyors only
	A23_LSC_C14 	: ConveyorLSC;
END_VAR
VAR
	//robot5 : RobotA23;
	//robot6 : RobotA23;
	wrapperA23 : WrapMachine;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="callHardware" Id="{0cc553bd-e8cb-4e01-bbeb-d162de020df2}">
      <Declaration><![CDATA[METHOD PRIVATE callHardware : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="runModules" Id="{391bad03-4ba2-4862-b86e-854fa76dcbef}">
      <Declaration><![CDATA[METHOD PRIVATE runModules : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Ld"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" />
                    <l2 n="Connectors" />
                    <v n="Id">5L</v>
                  </o>
                </l2>
                <v n="BranchCounter">1</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Method>
    <Method Name="setupHardware" Id="{a64c747f-a35f-4a39-8af5-03ecfd93413f}">
      <Declaration><![CDATA[METHOD PRIVATE setupHardware : BOOL
VAR
	iCornerGuardSlot : CornerGuard;
	iCardboardSlot : Cardboard;
	i : INT;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="A23">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="A23.callHardware">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="A23.setupHardware">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>