<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="A25" Id="{3b04d2e6-0b6c-4c36-b7dd-d9e45e2be25d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM A25
VAR_OUTPUT
	A25_SC_C22 		: ConveyorSC;
	A25_SC_C24 		: ConveyorSC;
	A25_SC_C26 		: ConveyorSC;
	A25_SC_C28 		: ConveyorSC;
	A25_SC_C30 		: ConveyorSC;
	
	A25_LSC_C23 	: ConveyorLSC; //these conveyors move the bundle sideways onto the output buffers
	A25_LSLCC_C25 	: ConveyorLSC;
	A25_LSLCC_C27 	: ConveyorLSC;
	A25_LSC_C29 	: ConveyorLSC;
	A25_SC_C31 		: ConveyorSC;
	A25_SC_C32 		: ConveyorSC;
	A25_SC_C33 		: ConveyorSC;
	A25_SC_C34 		: ConveyorSC;
	A25_SC_C35 		: ConveyorSC;
	A25_SC_C36 		: ConveyorSC;
	A25_SC_C37 		: ConveyorSC;
	A25_SC_C38 		: ConveyorSC;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="A25">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>