<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="Queue" Id="{cc03ee38-0c22-4ccc-9545-2ee091a456fb}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT Queue
VAR
	entrySize : ULINT; //no functionaility, only to force input a type for readability
	length : USINT := 0;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Queue">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>