<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="A24" Id="{9825abd9-77b4-48ca-9d54-54afdff6fff9}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM A24
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="A24">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>