<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="A25" Id="{3b04d2e6-0b6c-4c36-b7dd-d9e45e2be25d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM A25]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="A25">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>