<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MatchesMaterialType" Id="{f5e34751-cdf7-4c56-b6e9-cf2209b10594}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION MatchesMaterialType : BOOL
VAR_INPUT
	pair : REFERENCE TO PositionMaterials;
	materialPrefix : STRING;
END_VAR
VAR
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[MatchesMaterialType :=
	FIND(pair.top, materialPrefix) > 0 AND
	FIND(pair.left, materialPrefix) > 0 AND
	FIND(pair.right, materialPrefix) > 0 AND
	FIND(pair.bottom, materialPrefix) > 0 AND
	
	FIND(pair.topLeft, materialPrefix) > 0 AND
	FIND(pair.topRight, materialPrefix) > 0 AND
	FIND(pair.bottomLeft, materialPrefix) > 0 AND
	FIND(pair.bottomRight, materialPrefix) > 0 ;]]></ST>
    </Implementation>
    <LineIds Name="MatchesMaterialType">
      <LineId Id="31" Count="8" />
      <LineId Id="17" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>